esp_toml_version = 1.0
firmware_images_url = "https://github.com/Denis-VR/xiaozhi-esp32/releases/download/v3.0.0_ru/"

supported_apps = [
    "xiaozhi_esp32s3_v3_0_0_ru"
]

[xiaozhi_esp32s3_v3_0_0_ru]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "v3.0.0_ru.bin"
android_app_url = ""
ios_app_url = ""
